#### 1. Reverse an integer

In [1]:
def reverse_int(x):
    string = str(x)
    
    if string[0] == '-':
        return int('-'+string[:0:-1])
    else:
        return int(string[::-1])
    
print(reverse_int(96))


69


#### 2. Average Word Length

In [2]:
# For a given sentence find average word length
# Remove punctuations

import re

sentence_1 = "Hey! There do you love python?"
sentence_2 = "I need to work very hard to learn more about algorithms in Python!"

def avg_word_len(x):
    #remove punctuations
    sentence = re.sub(r'[^\w\s]', '', x)
    #Split sentence in words
    sentence = sentence.split()
    
    avg_length =  round(sum([len(w) for w in sentence])/len(sentence),2)
    return avg_length

avg_word_len(sentence_2)

4.08

#### 3. Add String

In [3]:
# Given two non-negative integers num1 and num2 represented as string, return the sum of num1 and num2.
# You must not use any built-in BigInteger library or convert the inputs to integer directly.

#Notes:
#Both num1 and num2 contains only digits 0-9.
#Both num1 and num2 does not contain any leading zero.

num1 = '364'
num2 = '1836'

def solution(num1,num2):
    eval(num1) + eval(num2)
    return str(eval(num1) + eval(num2))
            
print(solution(num1,num2))

2200


#### 4. First Unique Character

In [4]:
# Given a string, find the first non-repeating character in it and return its index. 
# If it doesn't exist, return -1. # Note: all the input strings are already lowercase.

from collections import Counter

string = 'lowercaselO'

def unique_ch(s):
    count = Counter(s.lower())
    
    # find the index
    for idx, ch in enumerate(s):
        if count[ch] == 1:
            return idx     
    return -1

unique_ch(string)


2

#### 5. Palindrome

In [5]:
# Given a non-empty string s, you may delete at most one character. Judge whether you can make it a palindrome.
# The string will only contain lowercase characters a-z.

s = 'radkar'

def test_palindrome(s):
    for indx in range(len(s)):
        word = ''.join(x for x in s if s.index(x) != indx) 
           
        #test for palindrome
        if word == word[::-1]: return True, word
        
    return word == word[::-1]
    
test_palindrome(s)

(True, 'rakar')

#### 6. Monotonic Arrays

In [6]:
# Given an array of integers, determine whether the array is monotonic or not.
A = [6, 5, 4, 4] 
B = [1,1,1,3,3,4,3,2,4,2]
C = [1,1,2,3,7]

def monotonic(a):
    test = all([a[i]>= a[i+1] for i in range(len(a)-1)]) or\
           all([a[i]<= a[i+1] for i in range(len(a)-1)])
    return test
monotonic(C)

True

#### 7. Move Zeros

In [7]:
#Given an array nums, write a function to move all zeroes to the end of it while maintaining the relative order of 
#the non-zero elements.

array1 = [0,1,0,3,12]
array2 = [1,7,0,0,8,0,10,12,0,4]

def move_zeros(x):
    zeros = x.count(0)
    x= [i for i in x if i !=0 ]
    x.extend([0]* zeros)
    return x
print(move_zeros(array2))

[1, 7, 8, 10, 12, 4, 0, 0, 0, 0]


#### 8.Fill the Blanks

In [8]:
# Given an array containing None values fill in the None values with most recent 
# non None value in the array

array1 = [1,None,2,3,None,None,5,None]

def backfill(x):
    res =[]
    valid = 0
    for num in (x):
        if num is not None:
            res.append(num)
            valid = num
        else:
            res.append(valid)
            
    return res
            
backfill(array1)
            

[1, 1, 2, 3, 3, 3, 5, 5]

#### 9. Matched and Mismatched Words

In [9]:
#Given two sentences, return an array that has the words that appear in one sentence and not
#the other and an array with the words in common. 

sentence1 = 'We are really pleased to meet you in our city'
sentence2 = 'The city was hit by a really heavy storm'

def soln_9(s1, s2):
    s1 = set(s1.split())
    s2 = set(s2.split())
    #common = list(s1.intersection(s2))
    return sorted(list(s1^s2)), list(s1&(s2))

soln_9(sentence1, sentence2)

(['The',
  'We',
  'a',
  'are',
  'by',
  'heavy',
  'hit',
  'in',
  'meet',
  'our',
  'pleased',
  'storm',
  'to',
  'was',
  'you'],
 ['city', 'really'])

#### 10. Prime Numbers Array

In [10]:
# Given k numbers which are less than n, return the set of prime number among them
# Note: The task is to write a program to print all Prime numbers in an Interval.
# Definition: A prime number is a natural number greater than 1 that has no positive divisors other than 1 and itself. 

n= 35
def prime_nos(n):
    lst = []
    for num in range(n):
        if num > 1:
            for i in range(2, num):
                if (num % i) == 0:
                    break
            else:
                lst.append(num)
    return lst
prime_nos(35)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31]

#### 11. Split a string

In [11]:
# Split a string to a list and remove whitespaces and integers greater than 5.
s ='In 1984 the was a great'

def str_to_list( str ) :
	#Insert your code here
	lst= []
	
	for x in str:
		try:
			if int(x) <= 5:
				lst.append(x)
		except:
			if  x != " ":
				lst.append(x)
	return lst
str_to_list(s)

['I',
 'n',
 '1',
 '4',
 't',
 'h',
 'e',
 'w',
 'a',
 's',
 'a',
 'g',
 'r',
 'e',
 'a',
 't']

#### 12. Fibonacci number

In [12]:
#Method 1 - Recursive
'''def fib(n):
    if n < 2:
        return n
    return fib(n-1) + fib(n-2)

fib(4)'''

#Method 2 Iterative Method

def fib2(n):
    l = [0]
    a,b = 0, 1
    for i in range(0,n):
        a, b = b, a +b
        l.append(a)
    return a, l
fib2(5)       

(5, [0, 1, 1, 2, 3, 5])

#### 13. Reverse String

In [13]:
s = "love python!"
#method 1
s = ''.join(s[-i] for i in range(1, len(s)+1))
print(s)
#method 2
s = s[::-1]
print(s)

## Another Variation
#Given a string, you need to reverse the order of characters 
#in each word within a sentence while still preserving whitespace and initial word order

def rev_str(s):
    s= [w[::-1] for w in s.split()]
    return ' '.join(w for w in s)
rev_str(s)
    

!nohtyp evol
love python!


'evol !nohtyp'

#### 14. Check two arrays are equivalent

In [14]:
word1 = ['a', 'cd']
word2 = ['ac', 'd']

def two_words_equivalent(w1, w2):
    return ''.join(i for i in w1) == ''.join(i for i in w2)

two_words_equivalent(word1, word2)

True

#### 15. Sum Matrix Diagonal

In [15]:
import numpy as np 

def sum_diagnoal(mat):
    n = len(mat)
    output = 0
    
    for i in range(n):
        output = output + mat[i][i]
        if i != n-1-i:
            output = output + mat[i][n-1-i]
        
    return output
mat = np.array([[1,2,3],[0,3,5],[1,1,1]])
print(mat)
sum_diagnoal(mat)

[[1 2 3]
 [0 3 5]
 [1 1 1]]


9

#### 16. Amrstrong Integer

In [16]:
#a number which is equal to the sum of cube of its digits
n = 123
def armstrong(n):
    return sum([int(str(n)[i])**3 for i in range(len(str(n)))]) == n

armstrong(370)

True

#### 17. Prime Numbers

In [17]:
n = 7

def prime(n):
    if n>1 and n < 3:
        return True
    for i in range(2, n):
        if n%i == 0:
            return False
            break
    else:
        return True
        
prime(6) 

False

#### 18. N- Largests Values in an array

In [18]:
#import numpy as np
#n = int(input('Enter an integer'))
def n_largest(n):
    
    arr = np.array([2,4,96, 54, 63, 14])
    if n <= len(arr): return arr[np.argsort(arr)[-n:]]
    else:
        return print(f'Enter an integer less than {len(arr)}')
        
n_largest(13)

Enter an integer less than 6


#### 19. Swap Two number

In [19]:
#Method 1 : Using temp variable
a, b = 2, 5
'''temp = a 
a = b
b = temp
print(a, b)'''

#Method 2 without temp variable
a, b = b, a 
print(a, b)


5 2


#### 20. Prime Factors of an integer

In [29]:
n = 56

def prime_factors(n):
    l = []
    for num in range(1,n+1):
        for i in range(2, num):
            if (num % i) == 0: break
        else:
            l.append(num)
    l = [x for x in  l if n%x == 0 ]
    return l
prime_factors(136)   

[1, 2, 17]

#### 21. Add two integers without arithmetic operator

In [31]:
def add_without_plus_operator(a, b):
    while b != 0:
        data = a & b
        a = a ^ b
        b = data << 1
    return a 
add_without_plus_operator(2, 22)

24

#### 22. Find missing number in an array

In [47]:
# In array with  1 - 100 with one number missing find the missing number
arr1 = np.arange(1,101)
arr2 = np.random.choice(arr1,99, replace=0)

ele = arr1[[ item not in arr2 for item in arr1]]


array([70])

#### 23. Find Duplicate in an array

In [56]:
arr = [4,1,4,2,6]
u, c = np.unique(arr, return_counts=True)

dup = u[c > 1]
print(f'There following are duplicated values; {list(dup)}')

There following are duplicated values; [4]


#### 24. Find all pairs in an array of integers whose sum is a given number

In [71]:
n= 8

arr = np.array(np.random.randint(10, size=(10), ))
def sol(A, n):
    for i in range(0, len(A)-1):
        for j in range(i+1, len(A)):
            if (A[i] + A[j]) == n:
                print(f"Pair {A[i]}, {A[j]}")
                return True
        return False
print(arr)        
sol(arr, n)

[7 5 6 6 1 5 2 3 0 5]
Pair 7, 1


True

#### 25 Compare two arrays equal in size

In [86]:
a1 = np.array(list(range(10))).reshape(2,5)
a2 = np.array(list(range(10))).reshape(5,2)
a1.shape == a2.shape

False

#### 26. Create a Vehicle class without any variables and methods

In [3]:
class Vehicle():
    pass

#### 27. Create a Class with instance attributes

In [8]:
#Write a Python program to create a Vehicle class with max_speed 
# and mileage instance attributes.
class Vehicle():
    def __init__(self, name, max_speed, mileage):
        self.name = name
        self.max_speed = max_speed
        self.mileage = mileage
        
modelX = Vehicle('sedan', 241, 12335)
print(f' ModelX has {modelX.mileage} mileage')


 ModelX has 12335 mileage


#### 28. Inheritance

In [14]:
#Create a child class Bus that will inherit all of the variables and methods
# of the Vehicle class

class Bus(Vehicle):
    
    def seating_capacity(self, capacity):
        return f"The seating capacity of a {self.name} is {capacity} passengers"

school_bus = Bus('FH', 56, 236541)
print(school_bus.seating_capacity(50))

The seating capacity of a FH is 50 passengers


In [17]:
class Vehicle:
    def __init__(self, name, mileage, capacity):
        self.name = name
        self.mileage = mileage
        self.capacity = capacity

    def fare(self):
        return self.capacity * 100

class Bus(Vehicle):
    pass

School_bus = Bus("School Volvo", 12, 50)
print("Total Bus fare is:", School_bus.fare())

Total Bus fare is: 5000


#### 29. Class Variables

In [16]:
class Vehicle():
    #class attribute
    color = 'white'
    def __init__(self, name, max_speed, mileage):
        self.name = name
        self.max_speed = max_speed
        self.mileage = mileage
        
class Bus(Vehicle):
    pass

class car(Vehicle):
    pass

v1 = Bus('Volvo', 20, 0)
print(f'{v1.name} is {v1.color}')

Volvo is white


In [9]:
def print_pattern(n):
    for i, j in enumerate(range(n)):
        print('#'*(j+1), )
        
print_pattern(5)

#
##
###
####
#####


In [ ]:
def pattern_2(n):
    for i in range(n+1):
        for j in range(i+1):
            print(j, end=" ")
        print('\n')
        
pattern_2(5)        

In [26]:
def ascii_pattern():
    num = 65
    row = 0
    letter =1
    while letter <= 26:
        for row in range(row+1):
            print(chr(num), end=" ")
            num += 1
            letter += 1
            row+= 1
        print('\r')
ascii_pattern()
        

A 
B C 
D E F 
G H I J 
K L M N O 
P Q R S T U 
V W X Y Z [ \ 


In [27]:
d = {'k1':10, 'k2':20}
d2 ={i:j+10 for i, j in d.items()}
d2

{'k1': 20, 'k2': 30}

In [37]:
g =[1,3,2,5,9]
g[-1:-4]

[]

In [ ]:
t = int(input())

n = 1
while n <= t:
    arr = map(int, input().split())
    